version: '2'
services:
  arrestcontrol-app:
    image: arrestcontrol
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://arrestcontrol-postgresql:5432/ArrestControl
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  arrestcontrol-postgresql:
    extends:
      file: postgresql.yml
      service: arrestcontrol-postgresql
